name: trep1
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - asttokens
  - backcall
  - beautifulsoup4
  - blas
  - boltons
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - cmake
  - conda
  - conda-build
  - conda-content-trust
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - decorator
  - executing
  - expat
  - ffmpeg
  - freetype
  - giflib
  - glob2
  - gmpy2
  - icu
  - idna
  - intel-openmp
  - ipython
  - jedi
  - jinja2
  - jpeg
  - jsonpatch
  - jsonpointer
  - krb5
  - lcms2
  - libarchive
  - libcurl
  - libffi
  - libiconv
  - liblief
  - libpng
  - libssh2
  - libtiff
  - libuv
  - libwebp
  - libwebp-base
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkginfo
  - pluggy
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - py-lief
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pysocks
  - python
  - python-libarchive-c
  - pytorch
  - pytorch-lightning
  - requests
  - setuptools
  - six
  - snappy
  - soupsieve
  - sqlite
  - tensorboard
  - tensorboard-data-server
  - tensorflow
  - termcolor
  - tornado
  - tqdm
  - typing-extensions
  - urllib3
  - wheel
  - xz
  - zipp
  - zlib
